const constant = {
  ACtIVITY_LIST: 'ACtIVITY_LIST',
  REMOVE_ACTIVITY:'REMOVE_ACTIVITY',
  UNCHECK_LIST: 'UNCHECK_LIST',
  LOGIN:'LOGIN',
  UPDATA_PARAMS:'UPDATA_PARAMS',
  RELETED_AFFAIRS: 'RELETED_AFFAIRS'
}
export default constant;